# Generated by Django 2.2.14 on 2021-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_Name', models.CharField(max_length=50)),
                ('profile_Img', models.ImageField(upload_to='pic')),
                ('des_Intro', models.TextField()),
                ('client_Email', models.EmailField(max_length=254)),
                ('jour_img1', models.ImageField(upload_to='')),
                ('jour_img2', models.ImageField(upload_to='')),
                ('jour_img3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Sh', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
                ('product_img', models.ImageField(upload_to='pics')),
                ('slugs', models.SlugField()),
            ],
        ),
    ]
